services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        environment:
            # Copy from:
            # https://one.dash.cloudflare.com/
            # Networks -> Connectors -> Cloudflare Tunnels -> <tunnel name> -> Edit
            - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
        network_mode: 'host'
    db:
        image: mariadb:12.0.2
        restart: unless-stopped
        cap_add:
            - SYS_ADMIN
        ulimits:
            memlock: 262144
            nproc: 262144
        environment:
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        networks:
            private:
    wordpress:
        image: wordpress:6.9.0-php8.5-apache
        restart: unless-stopped
        hostname: ${SITE_HOST}
        command:
            - apache2-foreground
            - -C
            - 'ServerName ${SITE_HOST}'
        volumes:
            - ./wp-content:/var/www/html/wp-content
            - ./.htaccess:/var/www/html/.htaccess:rw
        environment:
            VIRTUAL_HOST: ${SITE_HOST}
            WORDPRESS_DEBUG: true
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_CONFIG_EXTRA: |
                $$_SERVER['HTTPS'] = 'on';
                define('WP_HOME', 'https://${SITE_HOST}');
                define('WP_SITEURL', 'https://${SITE_HOST}');
        env_file:
            - .env
        depends_on:
            - db
        networks:
            private:
            public:
                aliases:
                    - ${SITE_HOST}.yxorp

volumes:
    db:

networks:
    private:
        driver: bridge
    public:
        name: yxorp
        external: true
